[project]
name = "dhakacart-api"
version = "1.0.0"
description = "Dhakacart API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "python-json-logger>=4.0.0",
    "uvicorn>=0.40.0",
]
